/**
 * GitHub Project Index System - Type Definitions
 * 
 * This module defines the core TypeScript interfaces for the GitHub project
 * indexing system, supporting Level 1 AI analysis with incremental updates.
 */

/**
 * Metadata for a GitHub project in the index.
 * 
 * Contains basic project information, Level 1 AI analysis results,
 * and fields supporting incremental updates.
 */
export interface ProjectMetadata {
  /** Project directory path relative to workspace root */
  directory: string;
  
  /** Project name (typically repository name) */
  name: string;
  
  /** Project description from repository */
  description: string;
  
  /** Full GitHub repository URL */
  repoUrl: string;
  
  /** Last update timestamp from GitHub (ISO 8601) */
  lastUpdated?: string;
  
  // Level 1 - AI Analysis
  
  /** Categorization from LLM analysis (e.g., ["llm基础", "推理引擎"]) */
  categories: string[];
  
  /** Technology/framework tags from LLM (e.g., ["python", "pytorch"]) */
  tags: string[];
  
  /** One-line AI-generated description */
  summary: string;
  
  /** Project complexity level */
  complexity: "simple" | "medium" | "advanced";
  
  /** Primary programming language */
  primaryLanguage: string;
  
  // Incremental update support
  
  /** Last analysis timestamp (ISO 8601) */
  lastAnalyzed?: string;
  
  /** Content hash for detecting changes */
  contentHash?: string;
}

/**
 * Result structure from LLM analysis endpoint.
 * 
 * This is the parsed response from the AI analysis call,
 * which is then used to populate ProjectMetadata.
 */
export interface AnalysisResult {
  /** Categorization from LLM analysis */
  categories: string[];
  
  /** Technology/framework tags from LLM */
  tags: string[];
  
  /** One-line description generated by LLM */
  summary: string;
  
  /** Project complexity assessment */
  complexity: "simple" | "medium" | "advanced";
  
  /** Primary programming language detected */
  primaryLanguage: string;
}

/**
 * Configuration for LLM API connection.
 * 
 * Supports OpenAI-compatible APIs (including Kimi).
 */
export interface LLMConfig {
  /** LLM provider type */
  provider: "openai" | "anthropic" | "ollama";
  
  /** Base URL for API endpoint */
  baseURL: string;
  
  /** Model identifier to use */
  model: string;
  
  /** API key (optional - can be loaded from environment) */
  apiKey?: string;
  
  /** Maximum tokens in response */
  maxTokens: number;
  
  /** Sampling temperature (0-2) */
  temperature: number;
}

/**
 * Main configuration for the indexer system.
 * 
 * Combines LLM configuration with file system paths.
 */
export interface Config {
  /** LLM API configuration */
  llm: LLMConfig;
  
  /** Directory containing GitHub project clones */
  githubDir: string;
  
  /** Output file path for the generated index */
  outputFile: string;
}
